[project]
name = "bio-ml-26"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "pashak12072002@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
bio-ml-26 = "bio_ml_26:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
